feat: migrate policy to support messages
gravitee-io/gravitee-policy-xml-json pull request #38
Opened 2023-06-22 09:06 UTC by ytvnr

BREAKING CHANGE: this version is using the latest dependencies introduced by gravitee 4.0

**Issue**

https://gravitee.atlassian.net/browse/APIM-1624

---
**Gravitee.io Automatic Deployment**

🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
 - use it directly by updating your project with version: `2.0.0`
 - download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/com/graviteesource/policy/gravitee-policy-xml-json/2.0.0/gravitee-policy-xml-json-2.0.0.zip)

2023-06-22 20:00 UTC, leleueri requested changes
LGTM in term of code but can you please adapt the plugin.properties file to define for each type of API on which phase it is accessible?

```
proxy=REQUEST,RESPONSE 
message=MESSAGE_REQUEST,MESSAGE_RESPONSE
```

cf slab page about  v4 "Conceptual changes"

2023-06-22 20:00 UTC, leleueri commented on .circleci/config.yml
Can you please update all the config to take into account alpha branchs during release ? (see https://github.com/gravitee-io/gravitee-policy-transformheaders/blob/master/.circleci/config.yml#L25 as an example)

2023-06-23 05:11 UTC, ytvnr commented on .circleci/config.yml
good catch, I totally forgot those things.

for the Breaking change, it is indicated in the commit, but I can add it to the PR description also

2023-06-23 11:58 UTC, leleueri approved these changes

2023-06-23 11:58 UTC, merged

2023-06-23 12:02 UTC, graviteeio commented
:tada: This PR is included in version 2.0.0-alpha.1 :tada:

The release is available on:
- `2.0.0-alpha.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-xml-json/releases/tag/2.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: